version: "3.8"

services:
  app:
    image: mba_estudo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    # Comando para o container não parar após a leitura de todas as camadas
    command: tail -f /dev/null
